export const static_products = [
    {
        product_id:1,
        index:'4MOVE1',
        producer:'FoodCare',
        name:'4MOVE Isotonic drink Multifruit',
        capacity:'500ml',
        image:'https://zapodaj.net/images/f966484b176dd.jpg',
        price:2.99,
        primary_unit:'szt',
        secondary_unit:'krt',
        quantity_in_secondary_unit: 12,
        sold_in_unit:'secondary',
        category_id:1,
        subcategory_id:11,
    },
    {
        product_id:2,
        index:'4MOVE2',
        producer:'FoodCare',
        name:'4MOVE Isotonic drink Orange',
        capacity:'500ml',
        image:'https://zapodaj.net/images/b1dd4a3761c68.jpg',
        price:2.95,
        primary_unit:'szt',
        secondary_unit:'krt',
        quantity_in_secondary_unit: 12,
        sold_in_unit:'secondary',
        category_id:1,
        subcategory_id:11,
    },
    {
        product_id:3,
        index:'JURA1',
        producer:'Jurajska',
        name:'Jurajska woda gazowana mała',
        capacity:'500ml',
        image:'https://zapodaj.net/images/da737bf6d5f6e.jpg',
        price:1.25,
        primary_unit:'szt',
        secondary_unit:'zgrz',
        quantity_in_secondary_unit: 30,
        sold_in_unit:'both',
        category_id:1,
        subcategory_id:13,
    },
    {
        product_id:4,
        index:'JURA2',
        producer:'Jurajska',
        name:'Jurajska woda niegazowana mała',
        capacity:'500ml',
        image:'https://zapodaj.net/images/dff2b9aa79ef8.jpg',
        price:1.25,
        primary_unit:'szt',
        secondary_unit:'zgrz',
        quantity_in_secondary_unit: 30,
        sold_in_unit:'both',
        category_id:1,
        subcategory_id:13,
    },
    {
        product_id:5,
        index:'NESTLE1',
        producer:'Nestle',
        name:'Nestle Pure Life woda gazowana',
        capacity:'1,5l',
        image:'https://zapodaj.net/images/86503237c772f.jpg',
        price:2.39,
        primary_unit:'szt',
        secondary_unit:'zgrz',
        quantity_in_secondary_unit: 6,
        sold_in_unit:'both',
        category_id:1,
        subcategory_id:13,
    },
    {
        product_id:6,
        index:'OWOZ1',
        producer:'Imported Fruits',
        name:'Arbuz',
        capacity:null,
        image:'https://zapodaj.net/images/c76502a8a768f.jpg',
        price:3.99,
        primary_unit:'kg',
        secondary_unit:null,
        quantity_in_secondary_unit: null,
        sold_in_unit:'primary',
        category_id:3,
        subcategory_id:32,
    },
    {
        product_id:7,
        index:'OWOZ2',
        producer:'Imported Fruits',
        name:'Banan',
        capacity:null,
        image:'https://zapodaj.net/images/03b1320f30407.jpg',
        price:3.25,
        primary_unit:'kg',
        secondary_unit:'krt',
        quantity_in_secondary_unit: 12,
        sold_in_unit:'both',
        category_id:3,
        subcategory_id:32,
    },
    {
        product_id:8,
        index:'OWOZ3',
        producer:'Imported Fruits',
        name:'Mango',
        capacity:null,
        image:'https://zapodaj.net/images/c221092830e66.jpg',
        price:3.25,
        primary_unit:'szt',
        secondary_unit:null,
        quantity_in_secondary_unit: null,
        sold_in_unit:'primary',
        category_id:3,
        subcategory_id:32,
    },
    {
        product_id:9,
        index:'OWOP1',
        producer:'Poland Fruits',
        name:'Śliwki węgierki',
        capacity:null,
        image:'https://zapodaj.net/images/1dd5893eeccd7.jpg',
        price:1.99,
        primary_unit:'kg',
        secondary_unit:null,
        quantity_in_secondary_unit: null,
        sold_in_unit:'primary',
        category_id:3,
        subcategory_id:31,
    },
    {
        product_id:10,
        index:'OWOP2',
        producer:'Poland Fruits',
        name:'Jabłka Champion',
        capacity:null,
        image:'https://zapodaj.net/images/a92e466c8ee6c.jpg',
        price:4.29,
        primary_unit:'kg',
        secondary_unit:null,
        quantity_in_secondary_unit: null,
        sold_in_unit:'primary',
        category_id:3,
        subcategory_id:31,
    },
    {
        product_id:11,
        index:'OWOP3',
        producer:'Poland Fruits',
        name:'Jabłka Golden Delicious',
        capacity:null,
        image:'https://zapodaj.net/images/34b77b5183c5f.jpg',
        price:2.75,
        primary_unit:'szt',
        secondary_unit:'krt',
        quantity_in_secondary_unit: 15,
        sold_in_unit:'both',
        category_id:3,
        subcategory_id:31,
    },







   /* {
        product_id:1,
        index:'',
        producer:'',
        name:'',
        capacity:'',
        image:'',
        price:12.99,
        primary_unit:'szt',
        secondary_unit:'krt',
        quantity_in_secondary_unit: 12,
        sold_in_unit:'secondary',
        category_id:0,
        subcategory_id:0,
    },*/

];